### ISSUE TITLE
Swift 4.2 release?

### ISSUE THREAD

**Issue by joeboyscout04** [negusoft/Polyglot#8]
Could you do a release to Cocoapods that is compatible with Swift 4.2?  There's some minor changes that make this library not compile in Swift 4.2.

**Comment by blurkidi** [comment]
Done! ✅

I had some trouble releasing the pod. I finally had to update my cocoapods to the latest version (which is still in beta) in order to pass validation, but it is all good now.

I released under 0.8.0, let me know if it is all good.
